# Generated by Django 5.2.1 on 2025-06-12 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_category', models.CharField(choices=[('prices_lists', 'Prices Lists'), ('general_information', 'General Information'), ('trips_and_adventure', 'Trips and Adventure')], default='prices_lists', max_length=50, verbose_name='rices Lists')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Title')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_banner', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload Banner')),
                ('checkin_time', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('checkout_time', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('trips_adventure_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trips and Adventure Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_template', to='app_template.apptemplatemodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload Image')),
                ('image_title', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_images', to='app_template.apptemplatemodel')),
            ],
        ),
    ]
