# Generated by Django 5.2.1 on 2025-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptemplatemodel',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
