# Generated by Django 5.2.1 on 2025-05-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload Image')),
                ('image_title', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.AlterField(
            model_name='apptemplatemodel',
            name='upload_banner',
            field=models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload Banner'),
        ),
        migrations.AddField(
            model_name='apptemplatemodel',
            name='additional_image',
            field=models.ManyToManyField(null=True, related_name='template_images', to='app_template.templateimagemodel'),
        ),
    ]
