# Generated by Django 5.2.1 on 2025-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0002_alter_apptemplatemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptemplatemodel',
            name='app_category',
            field=models.CharField(choices=[('prices_lists', 'Prices Lists'), ('general_information', 'General Information'), ('trips_and_adventure', 'Trips and Adventure')], default='prices_lists', max_length=50, verbose_name='prices Lists'),
        ),
    ]
