# Generated by Django 5.2.1 on 2025-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0002_templateimagemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplatemodel',
            name='additional_image',
        ),
        migrations.AddField(
            model_name='apptemplatemodel',
            name='additional_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
