# Generated by Django 5.2.1 on 2025-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0003_remove_apptemplatemodel_additional_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplatemodel',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='apptemplatemodel',
            name='additional_image',
            field=models.ManyToManyField(blank=True, null=True, related_name='template_images', to='app_template.templateimagemodel'),
        ),
    ]
