# Generated by Django 5.2.1 on 2025-05-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0004_remove_apptemplatemodel_additional_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_template', to='app_template.apptemplatemodel')),
            ],
        ),
    ]
