# Generated by Django 5.2.1 on 2025-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0005_productmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='apptemplatemodel',
            name='additional_image',
            field=models.ManyToManyField(blank=True, related_name='template_images', to='app_template.templateimagemodel'),
        ),
    ]
