# Generated by Django 5.2.1 on 2025-06-21 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0005_appvisitmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplatemodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='apptemplatemodel',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
