# Generated by Django 5.2.1 on 2025-05-31 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0006_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplatemodel',
            name='additional_image',
        ),
        migrations.AddField(
            model_name='templateimagemodel',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_images', to='app_template.apptemplatemodel'),
        ),
    ]
