# Generated by Django 5.2.1 on 2025-06-12 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_bots_images/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='chat_bots_csv/')),
                ('website_link', models.URLField(blank=True, null=True)),
                ('unique_id', models.UUIDField(blank=True, null=True)),
                ('count_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
