# Generated by Django 5.2.1 on 2025-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='description',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='count_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_bots_csv/'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_bots_images/'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='unique_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
