# Generated by Django 5.2.1 on 2025-06-12 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_template', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memebership_types', models.CharField(choices=[('we_free', 'We-Free'), ('we_basic', 'We-Basic'), ('we_pro', 'We-Pro'), ('we_enterprise', 'We-Enterprise')], default='we_free', max_length=40)),
                ('posting_generation', models.IntegerField(default=0)),
                ('custom_app', models.IntegerField(default=0)),
                ('is_ai_included', models.BooleanField(default=False)),
                ('ai_chatbot_message_quantity', models.IntegerField(default=0)),
                ('is_custom_design_included', models.BooleanField(default=False)),
                ('is_color_section_included', models.BooleanField(default=False)),
                ('is_only_logo', models.BooleanField(default=False)),
                ('is_wepro_branding', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PosterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload poster image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_posters', to='app_template.apptemplatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserMemberShipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='poster.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
