# Generated by Django 5.2.1 on 2025-06-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_template', '0007_remove_apptemplatemodel_additional_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='Upload poster image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_posters', to='app_template.apptemplatemodel')),
            ],
        ),
    ]
