# Generated by Django 5.2.1 on 2025-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBasePriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_generation', models.FloatField(default=0.0)),
                ('custom_app', models.FloatField(default=0.0)),
                ('ai_inclusion', models.FloatField(default=0.0)),
                ('custom_design_inclusion', models.FloatField(default=0.0)),
                ('color_design_inclusion', models.FloatField(default=0.0)),
                ('logo_design_inclusion', models.FloatField(default=0.0)),
                ('we_pro_branding', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='memebership_types',
            field=models.CharField(choices=[('we_free', 'We-Free'), ('we_basic', 'We-Basic'), ('we_pro', 'We-Pro'), ('we_enterprise', 'We-Enterprise')], default='we_free', max_length=40, unique=True),
        ),
    ]
