# Generated by Django 5.2.1 on 2025-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memebership_types', models.CharField(choices=[('we_free', 'We-Free'), ('we_basic', 'We-Basic'), ('we_pro', 'We-Pro'), ('we_enterprise', 'We-Enterprise')], default='we_free', max_length=40)),
                ('posting_generation', models.IntegerField(default=0)),
                ('custom_app', models.IntegerField(default=0)),
                ('is_ai_included', models.BooleanField(default=False)),
                ('is_custom_design_included', models.BooleanField(default=False)),
                ('is_color_section_included', models.BooleanField(default=False)),
                ('is_only_logo', models.BooleanField(default=False)),
                ('is_wepro_branding', models.BooleanField(default=False)),
            ],
        ),
    ]
