# Generated by Django 5.2.1 on 2025-06-13 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_featurebasepricemodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='price',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount in cents'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='processing', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_payment_intent_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
