# Generated by Django 5.2.1 on 2025-06-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_remove_membershipplan_price_membershipplan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
