# Generated by Django 5.2.1 on 2025-06-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_alter_membershipplan_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMemberShipPlan',
        ),
    ]
