# Generated by Django 5.2.1 on 2025-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_delete_usermembershipplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='memebership_types',
            field=models.CharField(choices=[('we_free', 'We-Free'), ('we_basic', 'We-Basic'), ('we_pro', 'We-Pro'), ('we_enterprise', 'We-Enterprise')], default='we_free', max_length=40),
        ),
    ]
