# Generated by Django 5.2.1 on 2025-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_alter_membershipplan_memebership_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
