# Generated by Django 5.2.1 on 2025-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0007_membershipplan_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='company logo image')),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('twiter_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('hotel_website_link', models.TextField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hotel_location', models.TextField(blank=True, null=True)),
                ('main_color', models.CharField(blank=True, max_length=200, null=True)),
                ('background_color', models.CharField(blank=True, max_length=200, null=True)),
                ('heading_text_color', models.CharField(blank=True, max_length=200, null=True)),
                ('text_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
