# Generated by Django 5.2.1 on 2025-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_brandmodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='app_template_images/', verbose_name='company profile image'),
        ),
    ]
